mcode/mcode-extraction-ui

electron/electron.js, electron/preload.js, react-app/src/components/Extract.js, react-app/src/components/ExtractionError.js, react-app/src/components/PatientData.js, react-app/src/components/ResultSidebar.js, react-app/src/stylesheets/Page.scss
The form on the Extract page was modified. The config file path and log file path fields now have file selectors instead of text inputs. When the user checks "Filter by start date" or "Filter by end date", a date picker appears under the checkbox, allowing the user to chose to and from dates.
The form on the Extract page was modified to use file and date pickers, and to update the toDate and fromDate variables based on input. preload.js and electron.js were modified to add functions to handle file selection.
The user selects config and log files using a file picker. The user is able to filter results by date.
Start the app with npm start. Click on "Extract New". Click on "Select Config File" or "Select Log File" to open the file selectors and choose files. Check "Filter by start date" to …
=> File and date pickers

electron/InMemoryTransport.js, react-app/src/components/LogList.js, react-app/src/components/ResultPage.js, react-app/src/components/ResultSidebar.js, react-app/src/stylesheets/Page.scss
Summary
Logger statistics display in the "Log File" dropdown in the sidebar of the result page.
Code Changes
- Changed return value of InMemoryTransport
- Changed LogList to account for new return value
- Modified sidebar to calculate number of errors, warnings, debug messages, and total messages
New Behavior
When you click on the Log File dropdown in the sidebar of the result page, the number of each type of message (excluding info-level messages) will appear in a list.
Testing Guidance
Run the app with npm start. Run extraction with any input that doesn't cause fatal errors. Click on "Log File" in the sidebar. The message counts will appear underneath.
=> Logger statistics

electron/extraction.js
In the past, a bug occasionally occurred where extractedData would be undefined, causing the app to crash instead of going to the error page. While I wasn't able to trigger the bug, I did identify where it might come from. The runExtraction() function in extraction.js previously returned one of two things:
- extractedData, if the call to mcodeApp() didn't throw an error
- null, if the call to mcodeApp() threw an error
The front-end extraction code in Extract.js then checks the return value to decide where to redirect:
```
if (value.extractedData === null) {
history.push('/extraction-error');
} else {
history.push('/results');
}
```
If mcodeApp() failed and returned undefined without throwing an error, this could cause the UI to crash.
The try block in the runExtraction() function now …
=> Added condition to handle extraction errors

react-app/src/components/ResultSidebar.js, react-app/src/stylesheets/ResultPage.scss
Previously, when the sidebar was longer than the window, part of it would get cut off and would be inaccessible. Now the sidebar has a scrollbar.
When the sidebar is longer than the window, it scrolls instead of having part of it cut off. Additionally, the Exit and Save buttons are sticky, so they are always visible.
- Modified CSS class for the sidebar-interior. 
- Created a new sidebar-button-container class, since nav-button-container didn't look right with the scrolling.
Use npm start to start the app. Click on "Extract New". Run extraction with any data that will not cause a fatal extraction error. Click on one of the drop-downs in the accordion to make it expand. If necessary, change the window size to make it shorter than the sidebar. A scrollbar will appear. You can now scroll the …
=> Make sidebar scroll when larger than window

electron/electron.js, electron/preload.js, react-app/src/components/ResultSidebar.js
Users can save the patient JSON schemas to a folder on their computer.
When the user clicks the "Save" button on the output page, a file explorer opens up, allowing them to select a folder to download the patient JSON schemas to. The page will display a success alert if saving succeeded, and an error alert if fs.writeFileSync() throws an error.
- Functions added to preload.js and electron.js to handle the backend of opening the file explorer and writing files
- onSave() function now has code in it
- Alerts that display when after the user saves (or fails to save) info
Start the app with npm start. Click "Extract New". Run extraction with any set of data that will not lead to fatal errors. Click "Save" and choose a folder. 
- If there is patient data to save, it will save, and an alert …
=> Save output

electron/InMemoryTransport.js, react-app/src/components/LogList.js, react-app/src/stylesheets/LogList.scss
The log messages are now color coded. The level is inside a badge, and the color of the badge changes based on the level.
The log messages are color-coded.
- Split up the message, level, and timestamp in the object returned by InMemoryTransport
- Modified LogList JSX to display the Badge with the level inside, the timestamp, and then the message
- Added function to LogList to determine which variant to use in Badge
- Added fixed-with-40px CSS class to LogList.scss so that the badges are all the same width
Start the app with npm start. Click on "Extract New". Run extraction with any data (both the error page and result page display the LogList component). If you use valid data, click on "Log File" in the sidebar of the result page. The LogList component will display.
=> Color coded log messages based on levels

react-app/src/components/Result.js, react-app/src/components/ResultPage.js, react-app/src/stylesheets/ResultPage.scss
The patient label in the sidebar of the result page now changes based on available information in the JSON schema.
Previously, the patients were all labelled "Patient X", where X was an iterator variable used to access the patient's bundle in extractedData. Now, the label changes based on available information:
1. If both an MRN and a name are available, they are displayed in this format: "MRN: First Last"
2. If either an MRN or a name is available, but not both, than the available data displays by itself
3. If neither an MRN nor a name is available, the patient resource ID displays
4. If a resource ID is unavailable, the old "Patient X" label is used.
- Added function to Result component and modified JSX in return statement
- Changes to CSS classes so that the resource IDs (which are …
=> Patient result label

electron/electron.js, electron/preload.js, react-app/package-lock.json, react-app/package.json, react-app/src/components/ConfigEditor.js, react-app/src/components/ConfigForm.js, react-app/src/components/Extract.js, react-app/src/components/ExtractionError.js, react-app/src/components/Home.js, react-app/src/components/LinkButton.js, react-app/src/stylesheets/Page.scss
The config editor now has functional "Back" and "Save As" buttons. Additionally, I found a fix for the bug where Buttons in LinkContainers always have active styling.
The config menu has a back button that redirects to the home page. The config editor has a back button that toggles back to the config menu. The config editor has a "Save As" button which allows the user to save the config schema. If the save process succeeds, a green success alert appears. If the save process fails, a red error alert appears and displays the error message. If the user cancels the save process, the save dialog disappears and no alert displays.
- Added "Back" button to config menu
- Added "Back" and "Save As" buttons to ConfigForm, along with associated functions
- Added save-config-as functions to backend …
=> Add Save As functionality and back buttons to config editor

electron/electron.js, electron/preload.js, react-app/src/components/ConfigEditor.js, react-app/src/stylesheets/Page.scss
The config editor menu now has a button to load a pre-existing schema.
The config menu has a button labelled "Load File". When clicked, it opens a dialog.showOpenDialog window and allows the user to select a JSON file. It then reads this file and stores its contents as a JSON object. The app then displays then ConfigForm placeholder, passing the config file to it.
- Made configJSON a state variable with associated functions
- Added functions to connect to backend for both selecting and reading the file
- Added error alert that displays at the bottom of the page if the process throws an error
Start the app with npm start. Click on "Configuration Editor". Click on "Load File". Select a file (the dialog will only allow you to select .json files). Click "Open". If the .json file you select is …
=> Config load button

react-app/src/components/Extract.js
The text and cancel button that display while the extractor runs are now centered.
Centered button and text on the Extract page.
- Added CSS classes to <p> containing processing message
- Added CSS class to div containing message and button
- Placed button inside a div with a CSS class
Testing Guidance
Start the app with npm start. Run extraction. The processing page will appear briefly. To look at the processing page for more than a couple of seconds, modify the conditional statements in lines 89 and 173 to change what displays:
Line 89 Original
`{!submitted && (`
Line 89 for Testing
`{submitted && ('
Line 173 Original
`{submitted && (`
Line 173 for Testing
'{!submitted && ('
The Extract page will now display the processing message, so you will be able to look at it for longer.
=> Centered processing text and cancel button

electron/electron.js, electron/extraction.js, electron/preload.js, package-lock.json, package.json, react-app/src/components/ConfigForm.js, react-app/src/components/SchemaFormUtils.js
The extraction process has been modified to accommodate the change to the config parameter of the mcodeApp function. Backend functions have been added to retrieve the config file schema.
The app behavior hasn't visibly changed.
- During extraction, extraction.js calls the getConfig function from the framework. This function takes the file path and returns the JSON object in that file. This object is passed to mcodeApp instead of the file path.
- schemaFormUtils, preload.js, and electron.js now have a chain of functions to retrieve the config file schema from the framework.
- Updated the mcode-extraction-framework dependency to the latest version of the develop branch
Start the app with npm start. Run extraction. It will not throw an error related to the data type of the config file.
In …
=> Load framework config

react-app/src/components/ConfigForm.js, react-app/src/components/schemaFormUtils.js, react-app/src/stylesheets/Page.scss
The config form now renders an accordion for the extractor array. Each extractor has its own accordion item. There is a dropdown to add new extractors. There is a button to sort the selected extractors by type; this button is disabled until there is at least one extractor added
The user can select extractors from a dropdown to add them to the array. The user can sort the extractors by type.
- Added ExtractorArray and Extractor components to schemaFormUtils.js
- Added CSS styles to Pages.scss
- Placed container around <Form /> in ConfigEditor so that there is a margin around the form, instead of inputs starting at stopping at the very edge of the window
Start the app with npm start. Click on "Configuration File Editor". Click on either "Create New" or "Load File". In the config form, …
=> Render extractor array

react-app/src/components/Extract.js, react-app/src/components/FilePicker.js, react-app/src/components/schemaFormUtils.js
The file picker used in the UI has been made into a separate component. schemaFormUtils uses this custom component to create a custom FileWidget.
The ConfigForm now renders a custom FileWidget for the patientIdCsvPath input.
- Added FilePicker component
- Modified extraction form to use the FilePicker (no visible change in behavior)
- Added custom FileWidget to schemaFormUtils, and added this widget to the widgets object. FileWidget receives props from the react-jsonschema-form. It passes the necessary functions and data (declaring them where necessary) to the FilePicker.
Start the app with npm start. Click on "Extract New". The file pickers on the extraction form will work as they always have. Go to the configuration editor. The patientIdCsvPath field (near the top of the page) renders …
=> Custom file picker

react-app/src/components/schemaFormUtils.js, react-app/src/stylesheets/Page.scss
The initial task was to create a custom string input to be rendered by the react-jsonschema-form Form for string fields. However, this turned out to be unnecessary. The width issue was fixed with CSS classes instead.
String fields are now limited to a max-width of 300px.
- Added input-width-limit to Page.scss
- Modified CSS classes in uiSchema - added input-width-limit where appropriate
- Modified CSS classes in uiSchema - removed page-text from all fields, since it was only added for testing purposes in a previous task and is no longer necessary.
- Export statement in schemaFormUtils was once again fixed
Start the app with npm start. Click on "Configuration Editor". Click on "Create New" or "Load". Many fields in the form will now have a maximum width of 300px. Fields that will be …
=> Custom string input

react-app/src/components/ConfigEditor.js, react-app/src/components/ConfigForm.js
This PR updates the 'Submit' button within the Configuration Editor to save the formData from the form component into a json file, rather than a placeholder object. 
I ended up using the Submit button that's provided as part of the `Form` component. This is because the only way to get the updated `formData` prop is by using the submit functionality built in to that component. I also moved the action bar containing the `Back` button from the `ConfigForm` to the `ConfigEditor` page because I felt that was a more intuitive location for it, but if others feel otherwise I can move it back.
=> Configuration Form is now saved to disk 

electron/electron.js, react-app/package-lock.json, react-app/package.json, react-app/public/index.html, react-app/src/components/ConfigForm.js, react-app/src/components/ExtractorArray.js, react-app/src/components/schemaFormUtils.js, react-app/src/stylesheets/Page.scss
This task took a look at managing validation outside of the default mechanism and adds validation back to our config editor UI. 
Given the fact that this code won't be remotely hosted and is designed to be run locally, we've decided that adding `unsafe-eval` to the HTML's content security policy doesn't introduce undue risk to our users. Therefore, for usability's sake, we will move forward with the built-in validation support.
In addition to flipping the validation switch this task ballooned into an investigation of existing issues with validation, resulting a few minor fixes and a bunch of future JIRA tickets. 
The fixes include: 
- Using the `window.maximize` function to full-screen the application on launch (this was going to be a subtask of STEAM-702, and the description has now been …
=> Add validation

react-app/src/components/ConfigEditor/ConfigEditor.js, react-app/src/components/ConfigEditor/templates/icare.json, react-app/src/components/ConfigEditor/templates/mcode.json
This PR adds a third option to the config editor page to "create from template" which will open the config editor with some fields already filled out. To start, I've added templates for "ICARE" which adds the extractors needed for ICARE and "mCODE" which adds all the extractors (or at least all the ones listed in the MEF's example config). To avoid possible confusion, there is also an alert that will tell the user that some fields have been filled out but others haven't.
To test:
- Go to the config editor
- Click "Create From Template" and pick an option
- See that the correct extractors were added and the config editor works as expected otherwise
=> Adding option to start config editor from template

react-app/src/components/ConfigEditor/ExtractorObject.js
Adds a Select All button for `checkbox` field constructorArgs in `ExtractorObject.js`. This Select All button mirrors the behavior of the Select All button in the file saver found in the extraction results page:
1. Auto-selects when all options are selected individually
2. Clicking the Select All button when all options are not selected will select the remaining options.
3. Clicking the Select All button when all options are selected will deselect all options.
=> Select All option for mask field

electron/helpers/configSchema.json, react-app/package-lock.json, react-app/package.json, react-app/src/components/ConfigEditor/CommonExtractorArgsAccordion.js, react-app/src/components/ConfigEditor/EditorForm.js, react-app/src/components/ConfigEditor/ExtractorAccordion.js, react-app/src/components/ConfigEditor/NotificationInfoAccordion.js, react-app/src/components/ConfigEditor/helpers/schemaFormUtils.js, react-app/src/stylesheets/Page.scss
This PR focuses on collapsing the Common Extractor Arguments and Notification Information sections in the configuration editor. This lets the focus remain on the more important (and required) Patient Id and Extractor sections. To do this, this PR makes a few key changes:
- Specified an order to the sections that are displayed so the Patient Id CSV File and Extractors come first
- Adds custom components for Common Extractor Arguments and Notification Information. These components wrap the fields in an accordion and then use RJSF's `SchemaField` to render the individiual fields. This was the best middle ground I could find for allowing us to control the surrounding rendering (the accordion) while still utilizing all the functionality RJSF provides for the individual fields (like the input …
=> Collapse Common Extractor Arguments and Notification Information sections

react-app/src/components/ConfigEditor/ConfigEditor.js
Address STEAM-795 by loading the mcode/icare templates in memory, avoiding the need for the backend to dynamically load these files. Since the loadFile functions are used in other ways, we didn't need to remove any electron-preload functions.
=> Load templates staticly, not dynamically

package.json, react-app/package.json, start.js
This PR adds a new script, `start.js`, that is called by `npm start` and checks for operating system, then calls the appropriate commands to start the app on that OS. The app should run exactly the same as before on Linux/Mac, but will now run properly in Windows when called with `npm start`
=> Adding start script to check for OS and call appropriate commands

electron/extraction.js
This PR adds a check for relative paths after the config file is loaded and before extraction starts, if there are relative paths in the patientIdCsvPath or any extractor filePath fields, an error will occur telling the user that they cannot use relative paths for these fields. To test: load a config file with a relative path in any extractor object or in the patientIdCsvPath field and you should see an error upon submitting.
I did consider various ways to immediately link the user to the config editor to fix this but then remembered that we had STEAM-716 (Design linking the configuration file editing with the Extract New page) in the backlog, so I went with a simpler solution for now, and I'll just note here that converting a relative path config file to an absolute path config file …
=> Disallowing relative filepaths in loaded config files
